# -*- coding: utf-8 -*-
"""Python Basics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AI7b45cSKB3NTeb-Nt1wbOexBLGslHLh
"""

print("Hello, world! Starting AI journey!")

# Variables
name = "Hiya"
age = 19
height = 5.9
is_student = True

# Print them
print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Is Student:", is_student)

age = 19

if 19 > 18:
    print("You can start your AI journey!")
else:
    print("Keep learning!")

def greet(Hiya):
    print("Hello", name)

greet("AI Learner")
greet("Future MLOps Engineer")

import random

number = random.randint(1, 10)
guess = int(input("Guess a number between 1 and 10: "))

if guess == 8:
    print("Congrats! You guessed it right.")
else:
    print("Wrong! The number was", number)

fruits = ["apple", "banana", "mango"]

print(fruits[0])   # apple
print(fruits[2])   # mango

fruits.append("orange")
fruits.remove("banana")
print(len(fruits))

student = {
    "name": "Rahul",
    "age": 20,
    "course": "Python"
}

print(student["name"])
print(student["course"])

colors = ("red", "green", "blue")

print(colors[1])

numbers = [1, 2, 3, 4, 5]

for num in numbers:
    if num % 2 == 0:
        print(num, "is even")
    else:
        print(num, "is odd")

num1 = float(input("Enter first number: "))
op = input("Enter operator (+, -, *, /): ")
num2 = float(input("Enter second number: "))

if op == "+":
    print("Result:", num1 + num2)
elif op == "-":
    print("Result:", num1 - num2)
elif op == "*":
    print("Result:", num1 * num2)
elif op == "/":
    print("Result:", num1 / num2)
else:
    print("Invalid operator")

tasks = []

while True:
    task = input("Enter a task (or type 'exit'): ")

    if task == "exit":
        break

    tasks.append(task)

print("Your Tasks:")
for t in tasks:
    print("-", t)

tasks = []

while True:
    action = input("add / remove / exit: ")

    if action == "add":
        task = input("Enter task: ")
        tasks.append(task)

    elif action == "remove":
        if len(tasks) == 0:
            print("No tasks to remove.")
            continue

        print("\nYour Tasks:")
        for i, t in enumerate(tasks, 1):
            print(i, "-", t)

        num = int(input("Enter task number to remove: "))
        tasks.pop(num - 1)

    elif action == "exit":
        break

print("\nFinal Tasks:")
for i, task in enumerate(tasks, 1):
    print(i, "-", task)



"""even_odd_checker.py"""

num = int(input("Enter a number: "))

if num % 2 == 0:
    print(num, "is Even")
else:
    print(num, "is Odd")

